name: integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: pip install flake8 setuptools pytest

      - name: Linter
        run: flake8 src/fuzzingtool --extend-ignore=E501,E731 --per-file-ignores="__init__.py:F401,F403,W292" --statistics

      - name: Package
        run: |
          python3 setup.py sdist
          cd dist
          pip3 install *

      - name: Test
        run: python3 -m pytest
