name: Pypi Uploader
 
on:
  release:
    types: [published]

jobs:
  pypi_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Installing dependencies"
        run: pip install setuptools wheel twine

      - name: "Build and publish to PyPI"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*