name: SonarCloud

on: 
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: "Installing dependencies"
        run: pip install setuptools virtualenv pytest pytest-cov

      - name: "Create virtualenv"
        run: |
          python3 -m venv env
          . env/bin/activate
          ls -la env/

      - name: "Build"
        run: |
          python3 setup.py sdist
          cd dist
          pip3 install *

      - name: "Generate Coverage"
        run: python3 -m pytest --cov=fuzzingtool --cov-report=xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nescau-ufla
            -Dsonar.projectKey=NESCAU-UFLA_FuzzingTool
            -Dsonar.python.version=3
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=env/lib/python3.8/site-packages/fuzzingtool/
            -Dsonar.tests=tests/