name: sast

on: push

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing bandit
        run: pip install bandit

      - name: Running bandit (1st round)
        run: python3 -m bandit -r src/fuzzingtool
        continue-on-error: true
      
      - name: Running bandit (2nd round)
        run: python3 -m bandit -ll -r src/fuzzingtool
